spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://34.66.74.89:5432/authorization-db?user=revatureBatch944&password=AdamRanieri
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  config:
    import:
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}
        healthCheckPath: /health
        health-check-interval: 120s
        service-name: ${spring.application.name}
server:
  port: 8080

