spring:
  application:
    name: auth-service
  datasource:
    url: ${AssignForceAuth}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#  config:
#    import: bootstrap.yaml
#  cloud:
#    consul:
#      config:
#        enabled: false
#      discovery:
#        instanceId: ${spring.application.name}
#        healthCheckPath: /health
#        health-check-interval: 5s
#        service-name: ${spring.application.name}
server:
  port: 8080

