apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    svc: cluster
spec:
  selector:
    app: auth
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort